# -*- mode: ruby -*-
# vi: set ft=ruby :

# Avoid having the worker starting before the master node
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

	config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Node
  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.synced_folder "../mnt/master", "/data-from-host"
	master.vm.hostname = "master.cluster.com"
    master.vm.network "private_network", ip: "192.168.219.2"
    # master.vm.network "forwarded_port", guest: 8080, guest_ip: "192.168.219.2", host: 8080, host_ip: "192.168.219.2"
    master.vm.provision "file", source: "net.yml", destination: "/home/vagrant/net.yml"
	master.vm.provision "file", source: "kube-flannel.yml", destination: "/home/vagrant/kube-flannel.yml"
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 2048
      v.cpus = 2
    end
    master.vm.provision "shell", path: "bootstrap_master.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "centos/7"      
	  worker.vm.hostname = "worker-#{i}.cluster.com"
      worker.vm.synced_folder "../mnt/worker-#{i}", "/data-from-host"      
	  worker.vm.network "private_network", ip: "192.168.219.#{2 + i}"
      worker.vm.provision "file", source: "net.yml", destination: "/home/vagrant/net.yml"
	  worker.vm.provision "file", source: "kube-flannel.yml", destination: "/home/vagrant/kube-flannel.yml"
      worker.vm.provider "virtualbox" do |v|
        v.name = "worker-#{i}"
        v.memory = 2048
        v.cpus = 1
      end
      worker.vm.provision "shell", path: "bootstrap_worker.sh"
    end
  end

end