apiVersion: v1
kind: Pod
metadata:
 name: nginx
 namespace: quota-demo-ns
spec:
 containers:
  - image: nginx
    name: nginx
    resources:
     limits: # Must be specified if ns have quotas set
      memory: "100Mi"
